cosmosLikeCoinNetworkConfig:
  name: likecoin-network

likecoinMigration:
  name: likecoin-migration

  container:
    imageRepository: likecoin/likecoin-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    tls:
      secretName: tls-likecoin-migration

  resources: {}

likenftMigration:
  name: likenft-migration

  container:
    imageRepository: likecoin/likenft-migration
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    tls:
      secretName: tls-likenft-migration

  resources: {}

migrationAdmin:
  name: migration-admin
  
  initContainer:
    imageRepository: nginx:alpine
    imagePullPolicy: IfNotPresent
    
  container:
    imageRepository: likecoin/migration-admin
    imagePullPolicy: IfNotPresent
    port: 80
    restartPolicy: Always

  service:
    port: 80
  ingress:
    prefix: /
    adminPrefix: /admin
    tls:
      secretName: tls-migration-admin

  resources: {}

migrationBackend:
  name: migration-backend
  env:
    BATCH_MINT_ITEM_PER_PAGE: "10"

  container:
    imageRepository: likecoin/like-migration-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  migrate: {}

  service:
    port: 80
  ingress:
    prefix: /
    adminPrefix: /admin
    tls:
      secretName: tls-migration-backend

  resources: {}

  worker:
    name: migration-backend-worker

    resources: {}

  scheduler:
    name: migration-backend-scheduler

    resources: {}

signerBackend:
  name: signer-backend

  migrate:
    backoffLimit: {}

  container:
    imageRepository: likecoin/like-signer-backend
    imagePullPolicy: IfNotPresent
    port: 8091

  service:
    port: 80

  resources: {}

  worker:
    name: signer-backend-worker

    resources: {}

  scheduler:
    name: signer-backend-scheduler

    resources: {}

likenftIndexer:
  name: likenft-indexer

  container:
    imageRepository: likecoin/likenft-indexer
    imagePullPolicy: IfNotPresent

  migrate: {}

  api:
    name: likenft-indexer-api

    container:
      port: 8091

    service:
      port: 80
    ingress:
      prefix: /
      tls:
        secretName: tls-likenft-indexer

    resources: {}

  worker:
    name: likenft-indexer-worker

    resources: {}

  scheduler:
    name: likenft-indexer-scheduler

    resources: {}

redis:
  name: redis
  container:
    imageRepository: redis
    imageVersion: 7
    port: 6379

  service:
    port: 6379

  resources: {}

nginx:
  name: nginx

  container:
    image: nginx
    imagePullPolicy: IfNotPresent
    port: 8000
    restartPolicy: Always

  service:
    port: 80

ingress:
  name: likecoin-op

  className: "nginx"

  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "true"
